version: 0.2

phases:
  build:
    commands:
      - echo "Copying index.html to S3 bucket..."
      - aws s3 cp index.html s3://luit-red-july-cicd-beta --acl public-read
      - if [ "$CODEBUILD_WEBHOOK_EVENT" == "PULL_REQUEST_MERGED" ]  ; 
        then aws s3 cp index.html s3://luit-red-july-cicd-prod/index.html --acl public-read; fi